# Generated by Django 4.2.25 on 2025-10-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at", "id"]},
        ),
    ]
