# Generated by Django 5.2.8 on 2025-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="negotiable",
            field=models.BooleanField(default=False),
        ),
    ]
